name: Init MySQL DB

on:
  push:  # permet de lancer manuellement depuis l'UI GitHub

jobs:
  init-db:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -uroot -proot --silent; then
              echo "✅ MySQL is up"
              break
            fi
            echo "Waiting for MySQL ($i)..."
            sleep 2
          done

      - name: Create harmonia database
        run: |
          mysql -h 127.0.0.1 -uroot -proot -e "CREATE DATABASE IF NOT EXISTS harmonia;"

      - name: Import SQL structure (optional)
        run: |
          mysql -h 127.0.0.1 -uroot -proot harmonia < infra/mysql/dump/harmoniaapi.sql
